FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache ca-certificates git docker-cli docker-cli-compose \
    && go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
